### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by drinkingsouls** [magiccart/magento-2-product-slider#4]
Hi MagePow.
I've having multiple issues installing this. Using Magento 2.4.2

If I add a product widget and select template to "Product Custom", I get console errors:
GET https://website.co.uk/static/version1625527000/frontend/Luma/theme/en_GB/magiccart/slick.js net::ERR_ABORTED 404
The slider does not show anywhere and there is no slick.js included in this download.

If I add slick.js myself I get:
Error filtering template: Invalid template file: 'productcustom.phtml' in module: 'Magiccart_Magicproduct' block's name: 'widget\product_0'
There doesn't seem to be a file productcustom.phtml?
where I place the widget in a page. If I place it in a widget area, nothing shows.

If I change the template to "Default" then the page fails to load and I get:

Error: Call to a member function getId() on null in /home/sites/domain/public/app/code/Magiccart/Magicproduct/Block/Widget/Product.php:64

I have included the Core module.

Thank you.

**Comment by magiccart** [comment]
Hi,
1. GET https://website.co.uk/static/version1625527000/frontend/Luma/theme/en_GB/magiccart/slick.js net::ERR_ABORTED 404
The issue cause you install missing core module. If you install manual you need install core module here https://github.com/magepow/magento-2-core
2. I have fixed it.

**Comment by drinkingsouls** [comment]
Thanks for looking into this.
As mentioned in my initial message, I have the Core module installed but slick.js doesn't seem to be included. I have updated the Core module again just now but the slick.js 404 still occurs.
Thank you.

**Comment by magiccart** [comment]
Hi, Please try run command composer remove magiccart/magicproduct
then run command composer require magiccart/magicproduct
If you using custom file in theme please find string "magiccart/slick" replace with "slick"
note: The new version maintenance by magepow.com we have replace magiccart/slick with "slick"
